# Generated by Django 5.0.7 on 2024-07-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_id', models.IntegerField()),
                ('team2_id', models.IntegerField()),
                ('league', models.IntegerField()),
                ('analysis', models.TextField()),
                ('winner_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
