# Generated by Django 5.0.7 on 2024-07-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API', '0002_delete_matchinsight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('time', models.CharField(max_length=255)),
                ('msg', models.CharField(max_length=255)),
            ],
        ),
    ]
